BOOTMAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
BACKLIGHT_ENABLE = no
SLEEP_LED_ENABLE = no
VISUALIZER_ENABLE = no
MIDI_ENABLE = no
AUDIO_ENABLE = no
UNICODE_ENABLE = no
TAP_DANCE_ENABLE = yes

ifndef QUANTUM_DIR
	include ../../../Makefile
endif
